#include "app/ClientCvars.hpp"

#include "client/Interpolation.hpp"
#include "console/ConsoleSystem.hpp"
#include "net/NetProtocol.hpp"

namespace lg {

void registerClientCvars(ConsoleSystem& console) {
  const CvarFlag archivedClient = CvarFlag::Archive | CvarFlag::Client;
  console.registerCvar({"cl_config_version", "Client config migration version.", 0, archivedClient, 0.0F, 100.0F});
  console.registerCvar({"sensitivity", "Mouse sensitivity multiplier.", 1.0F, archivedClient, 0.1F, 10.0F});
  console.registerCvar({"cl_aim_mode", "Aim mode: 0 relative 3D, 1 absolute 2D.", 0, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"cl_render_mode", "Renderer: 0 top-down, 1 first-person 3D.", 0, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"cl_fov", "Top-down camera view extent.", 90.0F, archivedClient, 45.0F, 140.0F});
  console.registerCvar({"cl_zoom_fov", "Field of view while +zoom is held.", 45.0F, archivedClient, 20.0F, 140.0F});
  console.registerCvar({"cl_zoom_sensitivity", "Mouse sensitivity multiplier while +zoom is held; zero auto-matches FOV.", 0.0F, archivedClient, 0.0F, 10.0F});
  console.registerCvar({"cl_camera_zoom", "Camera zoom multiplier; values above one zoom in.", 1.0F, archivedClient, 0.25F, 4.0F});
  console.registerCvar({"cl_rotate_view", "Rotate relative-aim view so facing direction points up.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_health_size", "Bottom-center health text scale.", 2.0F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"cl_showfps", "Show FPS, frame time, and renderer backend in the window title.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_show_frame_stats", "Show detailed CPU-side frame pacing diagnostics in the window title.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_showspeed", "Show current horizontal speed in Quake units per second.", true, archivedClient, {}, {}});
  console.registerCvar({"cl_show_net", "Show network diagnostics in the window title.", true, archivedClient, {}, {}});
  console.registerCvar({"net_sim_latency_ms", "Client UDP simulator extra one-way latency in ms; 60 adds about 120 ms RTT when applied to outgoing and incoming traffic.", 0, CvarFlag::Client, 0.0F, 5000.0F});
  console.registerCvar({"net_sim_jitter_ms", "Client UDP simulator per-datagram one-way jitter in ms around net_sim_latency_ms; delay is clamped at zero.", 0, CvarFlag::Client, 0.0F, 5000.0F});
  console.registerCvar({"net_sim_loss_percent", "Client UDP simulator independent datagram loss percent.", 0, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"net_sim_reorder_percent", "Client UDP simulator probabilistic datagram reorder percent; selected packets get a small extra hold so later packets can pass.", 0, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"net_sim_seed", "Client UDP simulator RNG seed; 0 uses the fixed default seed.", 0, CvarFlag::Client, 0.0F, 2147483647.0F});
  console.registerCvar({"cl_show_lagcomp", "Show lag compensation status and real rewind data when used.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_show_alive_counts", "Show Clan Arena alive counts on the HUD.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_interp_mode", "Remote interpolation mode: 0 legacy latest-pair, 1 buffered delay.", 1, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"cl_interp", "Remote player snapshot interpolation delay in seconds.", kDefaultSnapshotInterpolationDelaySeconds, archivedClient, 0.0F, 0.25F});
  console.registerCvar({"cl_legacy_frame_delay", "Deprecated legacy SDL_Delay(1) frame yield; prefer r_maxfps for pacing.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_local_render_prediction", "Render-only local movement prediction between fixed ticks; does not affect physics or hitreg.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_player_name", "Local player name sent to the server.", std::string{}, archivedClient, {}, {}});
  console.registerCvar({"s_enable", "Enable client sound effects.", true, archivedClient, {}, {}});
  console.registerCvar({"s_volume", "Client sound effect volume.", 0.35F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"s_footstep_volume", "Footstep sound volume multiplier.", 0.45F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"g_accel", "Authoritative ground acceleration; affects time to reach g_maxspeed.", 10.0F, CvarFlag::Client, 0.0F, 1000.0F, "10"});
  console.registerCvar({"g_airaccel", "Authoritative air acceleration.", 1.0F, CvarFlag::Client, 0.0F, 1000.0F, "1"});
  console.registerCvar({"g_aircontrol", "Enable QuakeWorld-style air control while holding forward.", false, CvarFlag::Client, {}, {}});
  console.registerCvar({"g_friction", "Authoritative grounded coasting friction; release movement to evaluate it.", 6.0F, CvarFlag::Client, 0.0F, 100.0F, "6"});
  console.registerCvar({"g_stopspeed", "Minimum speed used when calculating grounded friction.", 2.5F, CvarFlag::Client, 0.0F, 100.0F, "2.5 (pm_stopspeed 100)"});
  console.registerCvar({"g_maxspeed", "Authoritative sustained ground and air speed cap.", 8.0F, CvarFlag::Client, 0.1F, 100.0F, "8 (g_speed 320)"});
  console.registerCvar({"g_lg_knockback", "Authoritative LG knockback magnitude per second.", 1000.0F, CvarFlag::Client, 0.0F, kMaxLightningKnockback, "1000"});
  console.registerCvar({"g_lg_fire_hz", "Authoritative lightning gun damage instances per second.", 20.0F, CvarFlag::Client, kMinLightningFireHz, kMaxLightningFireHz});
  console.registerCvar({"g_rl_knockback", "Authoritative rocket knockback on the Q3 g_knockback scale.", 1000.0F, CvarFlag::Client, 0.0F, kMaxRocketKnockback, "1000"});
  console.registerCvar({"g_sg_damage", "Authoritative shotgun damage per pellet.", 5, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_mg_damage", "Authoritative machine gun damage per shot.", 5, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_lg_damage", "Authoritative lightning gun damage per second, distributed over g_lg_fire_hz instances.", 120, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_rg_damage", "Authoritative railgun damage per shot.", 80, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_rl_damage", "Authoritative rocket launcher direct and max splash damage.", 100, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_pg_damage", "Authoritative plasma gun direct hit damage.", 20, CvarFlag::Client, 1.0F, 500.0F});
  console.registerCvar({"g_vampirism", "Heal by this multiple of authoritative damage dealt.", 0.0F, CvarFlag::Client, 0.0F, 2.0F});
  console.registerCvar({"g_selfdamage", "Percent of self splash damage you take.", 100.0F, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"g_healthamount", "Authoritative player health amount on spawn and round start.", 100, CvarFlag::Client, 1.0F, 100000.0F});
  console.registerCvar({"g_flight", "Enable unrestricted flight symmetrically for both players.", false, CvarFlag::Client, {}, {}});
  console.registerCvar({"g_flightaccel", "Authoritative flight thrust acceleration.", 32.0F, CvarFlag::Client, 0.0F, 1000.0F});
  console.registerCvar({"g_flightmaxspeed", "Authoritative maximum flight speed.", 12.0F, CvarFlag::Client, 0.1F, 100.0F});
  console.registerCvar({"g_flightdamping", "Authoritative flight velocity damping.", 2.0F, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"crosshair_enable", "Draw the crosshair.", true, archivedClient, {}, {}});
  console.registerCvar({"crosshair_style", "Crosshair style: 0 cross, 1 cross and dot, 2 dot.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"crosshair_size", "Crosshair arm length in pixels.", 8.0F, archivedClient, 1.0F, 40.0F});
  console.registerCvar({"crosshair_thickness", "Crosshair thickness in pixels.", 2.0F, archivedClient, 1.0F, 10.0F});
  console.registerCvar({"crosshair_gap", "Crosshair center gap in pixels.", 3.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"crosshair_alpha", "Crosshair opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"crosshair_r", "Crosshair red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_g", "Crosshair green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_b", "Crosshair blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_enable", "Enable crosshair hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"crosshair_hit_r", "Crosshair hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_g", "Crosshair hit-feedback green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_b", "Crosshair hit-feedback blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_duration", "Crosshair hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"crosshair_hit_fade", "Gradually blend crosshair hit color back to base.", true, archivedClient, {}, {}});
  console.registerCvar({"vid_fullscreen", "Video fullscreen mode: 0 windowed, 1 borderless desktop, 2 exclusive fullscreen.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"vid_width", "Windowed width and requested exclusive fullscreen width.", 1280, archivedClient, 320.0F, 16384.0F});
  console.registerCvar({"vid_height", "Windowed height and requested exclusive fullscreen height.", 720, archivedClient, 200.0F, 16384.0F});
  console.registerCvar({"vid_refresh_hz", "Exclusive fullscreen refresh rate; zero uses desktop/default.", 0, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"vid_display", "Display index for fullscreen/window placement.", 0, archivedClient, 0.0F, 31.0F});
  console.registerCvar({"r_present_mode", "Renderer present mode: 0 FIFO/V-sync, 1 Mailbox, 2 Immediate.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_maxfps", "Manual CPU/render frame cap: 0 uncapped, otherwise frames per second.", 0, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_vsync", "Deprecated compatibility alias: 1 maps to r_present_mode 0, 0 maps to r_present_mode 2.", true, archivedClient, {}, {}});
  console.registerCvar({"g_playersize_xy", "Authoritative player X/Y radius scale.", 1.0F, CvarFlag::Client, 0.5F, 3.0F});
  console.registerCvar({"g_playersize_z", "Authoritative player height scale.", 1.0F, CvarFlag::Client, 0.5F, 3.0F});
  console.registerCvar({"r_beam_width", "Lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_beam_alpha", "Lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_beam_r", "Lightning beam red channel.", 74, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_g", "Lightning beam green channel.", 166, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_b", "Lightning beam blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_enable", "Enable local beam hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"r_beam_hit_r", "Local beam hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_g", "Local beam hit-feedback green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_b", "Local beam hit-feedback blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_duration", "Local beam hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_beam_hit_fade", "Gradually blend beam hit color back to base.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_beam_width", "Opponent lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_enemy_beam_alpha", "Opponent lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_beam_r", "Opponent lightning beam red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_beam_g", "Opponent lightning beam green channel.", 110, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_beam_b", "Opponent lightning beam blue channel.", 80, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker_enable", "Draw a center-screen hitmarker.", true, archivedClient, {}, {}});
  console.registerCvar({"r_hitmarker_duration", "Hitmarker duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_hitmarker_size", "Hitmarker arm length in pixels.", 10.0F, archivedClient, 2.0F, 40.0F});
  console.registerCvar({"r_hitmarker_thickness", "Hitmarker thickness in pixels.", 2.0F, archivedClient, 1.0F, 10.0F});
  console.registerCvar({"r_hitmarker_r", "Hitmarker red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker_g", "Hitmarker green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker_b", "Hitmarker blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_mode", "Damage number display: 0 off, 1 per damage instance, 2 per instance plus burst tally, 3 burst tally only, 4 world-space burst tally only.", 0, archivedClient, 0.0F, 4.0F});
  console.registerCvar({"r_damage_numbers_window", "Seconds without local damage before a burst tally resets.", 0.4F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_damage_numbers_duration", "Visual lifetime of each individual damage number.", 0.65F, archivedClient, 0.05F, 3.0F});
  console.registerCvar({"r_damage_numbers_size", "Damage number font scale.", 1.6F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_damage_numbers_alpha", "Damage number opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_damage_numbers_r", "Damage number red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_g", "Damage number green channel.", 236, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_b", "Damage number blue channel.", 128, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_offset_x", "Damage number horizontal screen offset from the crosshair.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_damage_numbers_offset_y", "Damage number vertical screen offset from the crosshair.", -46.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_r", "Enemy model red channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_g", "Enemy model green channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_b", "Enemy model blue channel.", 92, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_alpha", "Enemy model opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline_enable", "Draw an expanded enemy model outline.", true, archivedClient, {}, {}});
  console.registerCvar({"r_player_outline_style", "Player outline style: 0 geometry fallback, 1 screen-space mask request.", 0, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline_width", "Enemy model outline expansion in world units.", 0.045F, archivedClient, 0.0F, 0.5F});
  console.registerCvar({"r_enemy_outline_alpha", "Enemy model outline opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline_r", "Enemy model outline red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_outline_g", "Enemy model outline green channel.", 220, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_outline_b", "Enemy model outline blue channel.", 84, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_lean", "Enable Q3-style velocity lean on the enemy model.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_lean_scale", "Enemy model velocity lean multiplier; 1 approximates Q3 cg_runroll.", 1.0F, archivedClient, 0.0F, 3.0F, "cg_runroll 0.005"});
  console.registerCvar({"r_enemy_hit_enable", "Enable enemy hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_hit_r", "Enemy hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_g", "Enemy hit-feedback green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_b", "Enemy hit-feedback blue channel.", 198, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_duration", "Enemy hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_enemy_hit_fade", "Gradually blend hit color back to the base color.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_enable", "Draw floating enemy health bars.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_damage_only", "Only show enemy health bars after recent damage.", false, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_fade", "Fade enemy health bars during their damage-only duration.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_duration", "Seconds to show enemy health after damage.", 5.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"r_enemy_health_max_distance", "Hide enemy health bars beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_enemy_health_width", "Floating enemy health bar width in pixels.", 72.0F, archivedClient, 12.0F, 360.0F});
  console.registerCvar({"r_enemy_health_height", "Floating enemy health bar height in pixels.", 7.0F, archivedClient, 2.0F, 60.0F});
  console.registerCvar({"r_enemy_health_offset_z", "Floating enemy health bar vertical world offset above the model.", 0.35F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_enemy_health_offset_x", "Floating enemy health bar horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_health_offset_y", "Floating enemy health bar vertical screen offset.", -18.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_health_alpha", "Floating enemy health bar opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_health_r", "Floating enemy health bar red channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_health_g", "Floating enemy health bar green channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_health_b", "Floating enemy health bar blue channel.", 92, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name_enable", "Draw floating enemy name tags.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_name_alpha", "Floating enemy name tag opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_name_font_size", "Floating enemy name tag font scale.", 1.5F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_enemy_name_offset_z", "Floating enemy name tag vertical world offset.", 0.75F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_enemy_name_offset_x", "Floating enemy name tag horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_name_offset_y", "Floating enemy name tag vertical screen offset.", -34.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_name_max_distance", "Hide enemy name tags beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_enemy_name_r", "Floating enemy name tag red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name_g", "Floating enemy name tag green channel.", 235, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name_b", "Floating enemy name tag blue channel.", 235, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_width", "Teammate lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_teammate_beam_alpha", "Teammate lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_beam_r", "Teammate lightning beam red channel.", 80, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_g", "Teammate lightning beam green channel.", 220, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_b", "Teammate lightning beam blue channel.", 150, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_r", "Teammate model red channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_g", "Teammate model green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_b", "Teammate model blue channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_alpha", "Teammate model opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_outline_enable", "Draw an expanded teammate model outline.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_outline_width", "Teammate model outline expansion in world units.", 0.045F, archivedClient, 0.0F, 0.5F});
  console.registerCvar({"r_teammate_outline_alpha", "Teammate model outline opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_outline_r", "Teammate model outline red channel.", 128, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_outline_g", "Teammate model outline green channel.", 240, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_outline_b", "Teammate model outline blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_lean", "Enable Q3-style velocity lean on teammate models.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_lean_scale", "Teammate model velocity lean multiplier.", 1.0F, archivedClient, 0.0F, 3.0F});

  console.registerCvar({"r_teammate_health_enable", "Draw floating teammate health bars.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_damage_only", "Only show teammate health bars after recent damage.", false, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_fade", "Fade teammate health bars during their damage-only duration.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_duration", "Seconds to show teammate health after damage.", 5.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"r_teammate_health_max_distance", "Hide teammate health bars beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_teammate_health_width", "Floating teammate health bar width in pixels.", 72.0F, archivedClient, 12.0F, 360.0F});
  console.registerCvar({"r_teammate_health_height", "Floating teammate health bar height in pixels.", 7.0F, archivedClient, 2.0F, 60.0F});
  console.registerCvar({"r_teammate_health_offset_z", "Floating teammate health bar vertical world offset.", 0.35F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_teammate_health_offset_x", "Floating teammate health bar horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_health_offset_y", "Floating teammate health bar vertical screen offset.", -18.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_health_alpha", "Floating teammate health bar opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_health_r", "Floating teammate health bar red channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_health_g", "Floating teammate health bar green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_health_b", "Floating teammate health bar blue channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name_enable", "Draw floating teammate name tags.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_name_alpha", "Floating teammate name tag opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_name_font_size", "Floating teammate name tag font scale.", 1.5F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_teammate_name_offset_z", "Floating teammate name tag vertical world offset.", 0.75F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_teammate_name_offset_x", "Floating teammate name tag horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_name_offset_y", "Floating teammate name tag vertical screen offset.", -34.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_name_max_distance", "Hide teammate name tags beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_teammate_name_r", "Floating teammate name tag red channel.", 210, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name_g", "Floating teammate name tag green channel.", 245, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name_b", "Floating teammate name tag blue channel.", 255, archivedClient, 0.0F, 255.0F});
}

} // namespace lg
