#include "app/ClientCvars.hpp"

#include "client/Interpolation.hpp"
#include "console/ConsoleSystem.hpp"
#include "net/NetProtocol.hpp"
#include "sim/GameplayCvars.hpp"

namespace lg {

void registerClientCvars(ConsoleSystem& console) {
  const CvarFlag archivedClient = CvarFlag::Archive | CvarFlag::Client;
  console.registerCvar({"cl_config_version", "Client config migration version.", 0, archivedClient, 0.0F, 100.0F});
  console.registerCvar({"sensitivity", "Mouse sensitivity using the Q3/QL m_yaw 0.022 scale.", 5.0F, archivedClient, 0.0F, 100.0F, "5"});
  console.registerCvar({"cl_mouseAccel", "Quake Live mouse acceleration amount.", 0.0F, archivedClient, 0.0F, 1000.0F, "0"});
  console.registerCvar({"cl_mouseAccelPower", "Quake Live mouse acceleration power curve.", 2.0F, archivedClient, 1.0F, 10.0F, "2"});
  console.registerCvar({"cl_mouseAccelOffset", "Quake Live mouse speed threshold before acceleration applies.", 0.0F, archivedClient, 0.0F, 1000.0F, "0"});
  console.registerCvar({"cl_mouseSensCap", "Quake Live accelerated sensitivity cap; zero disables the cap.", 0.0F, archivedClient, 0.0F, 100.0F, "0"});
  console.registerCvar({"cl_fov", "First-person vertical field of view in degrees.", 90.0F, archivedClient, 45.0F, 140.0F});
  console.registerCvar({"cl_zoom_fov", "Field of view while +zoom is held.", 45.0F, archivedClient, 20.0F, 140.0F});
  console.registerCvar({"cl_zoom_sensitivity", "First-person mouse sensitivity multiplier while +zoom is held; zero auto-matches FOV.", 0.0F, archivedClient, 0.0F, 10.0F});
  console.registerCvar({"cl_death_spectate_threshold", "Respawn delay in seconds at which a dead player switches to a living teammate after the camera hold.", 3.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"cl_death_camera_hold", "Seconds to retain the local death-position view before teammate spectating is allowed.", 0.5F, archivedClient, 0.0F, 10.0F});
  console.registerCvar({"cl_death_desaturation", "Strength of the grey death-view treatment: 0 off, 1 full.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"cl_viewmodel_motion_scale", "Master scale for client-only first-person weapon motion; zero disables all motion.", 1.0F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_viewmodel_bob_scale", "Locomotion bob scale for the first-person weapon.", 0.65F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_viewmodel_sway_scale", "Mouse-driven sway scale for the first-person weapon.", 0.55F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_viewmodel_inertia_scale", "Movement acceleration and braking response scale for the first-person weapon.", 0.55F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_viewmodel_landing_scale", "Jump float and landing compression scale for the first-person weapon.", 0.65F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_camera_position_response", "Optional subtle translation-only camera response to viewmodel motion; zero disables it.", 0.0F, archivedClient, 0.0F, 0.15F});
  console.registerCvar({"cl_health_size", "Health HUD scale.", 2.0F, archivedClient, 0.5F, 20.0F});
  console.registerCvar({"cl_health_style", "Health HUD style: 0 bottom-left bar, 1 centered number, 2 crosshair number and ammo.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_speed_size", "Crosshair speed text scale.", 1.5F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"cl_weapon_bar_size", "Left weapon/ammo HUD scale.", 1.75F, archivedClient, 0.5F, 4.0F});
  console.registerCvar({"r_ui_font", "UI TTF/OTF font file. Looks in assets/fonts, assets/font, or accepts an absolute local path.", std::string{"bahnschrift.ttf"}, archivedClient, {}, {}});
  console.registerCvar({"cl_showfps", "Show an FPS counter on the HUD.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_showfps_size", "HUD FPS counter scale.", 1.6F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"cl_showfps_titlebar", "Show FPS, frame time, and renderer backend in the window title.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_show_frame_stats", "Show detailed CPU-side frame pacing diagnostics in the window title.", false, archivedClient, {}, {}});
  console.registerCvar({"r_perf", "Show client performance diagnostics on the HUD.", false, archivedClient, {}, {}});
  console.registerCvar({"r_perf_detail", "Show expanded client performance diagnostic breakdown.", false, archivedClient, {}, {}});
  console.registerCvar({"r_perf_reset", "Clear client performance diagnostic sample history once, then reset.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_showspeed", "Show current horizontal speed in Quake units per second.", true, archivedClient, {}, {}});
  console.registerCvar({"cg_ground_debug", "Show ground/slope movement diagnostics on the HUD: 0 off, 1 position/angles/ground, 2 detailed velocity state.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_show_net", "Show network diagnostics in the window title.", true, archivedClient, {}, {}});
  console.registerCvar({"cl_netgraph", "Network HUD: 0 off, 1 compact, 2 expanded history graph.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"cl_netgraph_scale", "Scale of the network HUD panel and text.", 1.75F, archivedClient, 0.75F, 3.0F});
  console.registerCvar({"net_sim_latency_ms", "Client UDP simulator extra one-way latency in ms; 60 adds about 120 ms RTT when applied to outgoing and incoming traffic.", 0, CvarFlag::Client, 0.0F, 5000.0F});
  console.registerCvar({"net_sim_jitter_ms", "Client UDP simulator per-datagram one-way jitter in ms around net_sim_latency_ms; delay is clamped at zero.", 0, CvarFlag::Client, 0.0F, 5000.0F});
  console.registerCvar({"net_sim_loss_percent", "Client UDP simulator independent datagram loss percent.", 0, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"net_sim_reorder_percent", "Client UDP simulator probabilistic datagram reorder percent; selected packets get a small extra hold so later packets can pass.", 0, CvarFlag::Client, 0.0F, 100.0F});
  console.registerCvar({"net_sim_seed", "Client UDP simulator RNG seed; 0 uses the fixed default seed.", 0, CvarFlag::Client, 0.0F, 2147483647.0F});
  console.registerCvar({"cl_show_lagcomp", "Show lag compensation status and real rewind data when used.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_show_alive_counts", "Show Clan Arena alive counts on the HUD.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_interp_mode", "Remote interpolation mode: 0 legacy latest-pair, 1 buffered delay.", 1, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"cl_interp", "Remote player snapshot interpolation delay in seconds.", kDefaultSnapshotInterpolationDelaySeconds, archivedClient, 0.0F, 0.25F});
  console.registerCvar({"cl_interp_adaptive", "Adapt the interpolation buffer to measured snapshot jitter.", true, archivedClient, {}, {}});
  console.registerCvar({"cl_interp_min", "Minimum adaptive interpolation delay in seconds.", 0.016F, archivedClient, 0.0F, 0.25F});
  console.registerCvar({"cl_interp_max", "Maximum adaptive interpolation delay in seconds.", 0.064F, archivedClient, 0.0F, 0.25F});
  console.registerCvar({"cl_interp_extrapolate", "Legacy compatibility setting; buffered interpolation now holds the newest authoritative snapshot during underrun.", 0.016F, archivedClient, 0.0F, 0.05F});
  console.registerCvar({"cl_legacy_frame_delay", "Deprecated legacy SDL_Delay(1) frame yield; prefer r_maxfps for pacing.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_local_render_prediction", "Render-only local movement prediction between fixed ticks; does not affect physics or hitreg.", false, archivedClient, {}, {}});
  console.registerCvar({"cl_player_name", "Local player name sent to the server.", std::string{}, archivedClient, {}, {}});
  console.registerCvar({"s_enable", "Enable client sound effects.", true, archivedClient, {}, {}});
  console.registerCvar({"s_volume", "Client sound effect volume.", 0.35F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"s_lg_fire_volume", "Lightning gun firing loop volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_rg_fire_volume", "Railgun fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_rg_ready_volume", "Railgun ready chime volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_rl_fire_volume", "Rocket launcher fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_rl_explosion_volume", "Rocket and grenade explosion sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_mg_fire_volume", "Machine gun fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_sg_fire_volume", "Shotgun fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_gl_fire_volume", "Grenade launcher fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_gl_bounce_volume", "Grenade bounce sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_pg_fire_volume", "Plasma gun fire sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_hit_volume", "Hit confirmation sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_frag_volume", "Frag/kill sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_pain_volume", "Pain grunt sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_footstep_volume", "Footstep sound volume multiplier.", 0.45F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_round_win_volume", "Round win sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_round_loss_volume", "Round loss sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  console.registerCvar({"s_countdown_volume", "Round countdown sound volume multiplier.", 1.0F, CvarFlag::Client, 0.0F, 1.0F});
  registerGameplayCvars(console, CvarFlag::Client);
  console.registerCvar({"crosshair", "Draw the crosshair.", true, archivedClient, {}, {}});
  console.registerCvar({"crosshair_style", "Crosshair style: 0 gapped cross, 1 cross, 2 no main shape, 3 ring.", 0, archivedClient, 0.0F, 3.0F});
  console.registerCvar({"crosshair_size", "Crosshair arm length in pixels.", 8.0F, archivedClient, 1.0F, 40.0F});
  console.registerCvar({"crosshair_width", "Crosshair line width in pixels.", 2.0F, archivedClient, 1.0F, 10.0F});
  console.registerCvar({"crosshair_gap", "Crosshair center gap in pixels.", 3.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"crosshair_dot", "Draw a center dot over any crosshair style.", false, archivedClient, {}, {}});
  console.registerCvar({"crosshair_dot_width", "Crosshair center dot size in pixels.", 2.0F, archivedClient, 1.0F, 20.0F});
  console.registerCvar({"crosshair_outline", "Draw a black outline behind the crosshair and dot.", false, archivedClient, {}, {}});
  console.registerCvar({"crosshair_outline_width", "Crosshair outline width in pixels.", 1.0F, archivedClient, 0.0F, 10.0F});
  console.registerCvar({"crosshair_alpha", "Crosshair opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"crosshair_r", "Crosshair red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_g", "Crosshair green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_b", "Crosshair blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit", "Enable crosshair hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"crosshair_hit_r", "Crosshair hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_g", "Crosshair hit-feedback green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_b", "Crosshair hit-feedback blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"crosshair_hit_duration", "Crosshair hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"crosshair_hit_fade", "Gradually blend crosshair hit color back to base.", true, archivedClient, {}, {}});
  console.registerCvar({"vid_fullscreen", "Video fullscreen mode: 0 windowed, 1 borderless desktop, 2 exclusive fullscreen.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"vid_width", "Windowed width and requested exclusive fullscreen width.", 1280, archivedClient, 320.0F, 16384.0F});
  console.registerCvar({"vid_height", "Windowed height and requested exclusive fullscreen height.", 720, archivedClient, 200.0F, 16384.0F});
  console.registerCvar({"vid_refresh_hz", "Exclusive fullscreen refresh rate; zero uses desktop/default.", 0, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"vid_display", "Display index for fullscreen/window placement.", 0, archivedClient, 0.0F, 31.0F});
  console.registerCvar({"r_present_mode", "Renderer present mode: 0 FIFO/V-sync, 1 Mailbox, 2 Immediate.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_maxfps", "Manual CPU/render frame cap: 0 uncapped, otherwise frames per second.", 0, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_vsync", "Deprecated compatibility alias: 1 maps to r_present_mode 0, 0 maps to r_present_mode 2.", true, archivedClient, {}, {}});
  console.registerCvar({"r_frustum_cull", "Cull remote player geometry outside the first-person camera frustum.", true, archivedClient, {}, {}});
  console.registerCvar({"r_texture_filter", "World texture filtering: 0 nearest, 1 bilinear with mipmaps, 2 trilinear with mipmaps.", 2, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_texture_anisotropy", "World texture anisotropic filtering level; clamped to 1, 2, 4, 8, or 16.", 8, archivedClient, 1.0F, 16.0F});
  console.registerCvar({"r_texture_lod_bias", "World texture mip LOD bias; positive values choose blurrier, more stable mip levels.", 0.5F, archivedClient, -2.0F, 4.0F});
  console.registerCvar({"r_draw_remote_players", "Draw remote player body models.", true, archivedClient, {}, {}});
  console.registerCvar({"r_draw_remote_weapons", "Draw remote held weapon models.", true, archivedClient, {}, {}});
  console.registerCvar({"r_show_weapons", "Draw local first-person weapon models.", true, archivedClient, {}, {}});
  console.registerCvar({"r_weapon_pos", "First-person weapon position: 0 center, 1 wide right, 2 wide left.", 0, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_draw_player_outlines", "Draw player outlines.", true, archivedClient, {}, {}});
  console.registerCvar({"r_beam_width", "Lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_beam_alpha", "Lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_beam_r", "Lightning beam red channel.", 74, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_g", "Lightning beam green channel.", 166, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_b", "Lightning beam blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit", "Enable local beam hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"r_beam_hit_r", "Local beam hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_g", "Local beam hit-feedback green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_b", "Local beam hit-feedback blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_beam_hit_duration", "Local beam hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_beam_hit_fade", "Gradually blend beam hit color back to base.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_beam_width", "Opponent lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_enemy_beam_alpha", "Opponent lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_beam_r", "Opponent lightning beam red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_beam_g", "Opponent lightning beam green channel.", 110, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_beam_b", "Opponent lightning beam blue channel.", 80, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker", "Draw a center-screen hitmarker.", true, archivedClient, {}, {}});
  console.registerCvar({"r_hitmarker_duration", "Hitmarker duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_hitmarker_size", "Hitmarker arm length in pixels.", 10.0F, archivedClient, 2.0F, 40.0F});
  console.registerCvar({"r_hitmarker_width", "Hitmarker line width in pixels.", 2.0F, archivedClient, 1.0F, 10.0F});
  console.registerCvar({"r_hitmarker_r", "Hitmarker red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker_g", "Hitmarker green channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_hitmarker_b", "Hitmarker blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_sg_weapon_model_start", "Draw shotgun fire from the remote weapon model instead of the gameplay muzzle.", false, archivedClient, {}, {}});
  console.registerCvar({"r_damage_numbers_mode", "World-space damage number display: 0 off, 1 per damage instance, 2 per instance plus burst tally, 3 burst tally only.", 0, archivedClient, 0.0F, 3.0F});
  console.registerCvar({"r_damage_numbers_window", "Seconds without local damage before a burst tally resets.", 0.4F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_damage_numbers_duration", "Visual lifetime of each individual damage number.", 0.65F, archivedClient, 0.05F, 3.0F});
  console.registerCvar({"r_damage_numbers_size", "Damage number font scale.", 1.6F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_damage_numbers_alpha", "Damage number opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_damage_numbers_r", "Damage number red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_g", "Damage number green channel.", 236, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_b", "Damage number blue channel.", 128, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_damage_numbers_damage_color", "Blend damage numbers from the configured color toward red as damage increases.", false, archivedClient, {}, {}});
  console.registerCvar({"r_damage_numbers_offset_x", "Damage number horizontal screen offset from the projected world anchor.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_damage_numbers_offset_y", "Damage number vertical screen offset from the projected world anchor.", -46.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_r", "Enemy model red channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_g", "Enemy model green channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_b", "Enemy model blue channel.", 92, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_alpha", "Enemy model opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_player_model", "Remote player model: 0 legacy boxes, 1 animated GLB.", 1, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline", "Draw enemy screen-space outline.", true, archivedClient, {}, {}});
  console.registerCvar({"r_player_outline_style", "Player outline style: 0 legacy geometry fallback, 1 screen-space mask.", 1, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline_width", "Enemy outline width in final display pixels (1-6 px intended).", 3.0F, archivedClient, 0.0F, 6.0F});
  console.registerCvar({"r_enemy_outline_alpha", "Enemy outline opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_outline_r", "Enemy model outline red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_outline_g", "Enemy model outline green channel.", 220, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_outline_b", "Enemy model outline blue channel.", 84, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_lean", "Enable Q3-style velocity lean on the enemy model.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_lean_scale", "Enemy model velocity lean multiplier; 1 approximates Q3 cg_runroll.", 1.0F, archivedClient, 0.0F, 3.0F, "cg_runroll 0.005"});
  console.registerCvar({"r_enemy_hit", "Enable enemy hit-color feedback.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_hit_r", "Enemy hit-feedback red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_g", "Enemy hit-feedback green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_b", "Enemy hit-feedback blue channel.", 198, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_hit_duration", "Enemy hit-color duration in seconds.", 0.12F, archivedClient, 0.0F, 2.0F});
  console.registerCvar({"r_enemy_hit_fade", "Gradually blend hit color back to the base color.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health", "Draw floating enemy health bars.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_damage_only", "Only show enemy health bars after recent damage.", false, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_fade", "Fade enemy health bars during their damage-only duration.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_health_duration", "Seconds to show enemy health after damage.", 5.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"r_enemy_health_max_distance", "Hide enemy health bars beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_enemy_health_width", "Floating enemy health bar width in pixels.", 72.0F, archivedClient, 12.0F, 360.0F});
  console.registerCvar({"r_enemy_health_height", "Floating enemy health bar height in pixels.", 7.0F, archivedClient, 2.0F, 60.0F});
  console.registerCvar({"r_enemy_health_offset_z", "Floating enemy health bar vertical world offset above the model.", 0.35F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_enemy_health_offset_x", "Floating enemy health bar horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_health_offset_y", "Floating enemy health bar vertical screen offset.", -18.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_health_alpha", "Floating enemy health bar opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_health_r", "Floating enemy health bar red channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_health_g", "Floating enemy health bar green channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_health_b", "Floating enemy health bar blue channel.", 92, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name", "Draw floating enemy name tags.", true, archivedClient, {}, {}});
  console.registerCvar({"r_enemy_name_alpha", "Floating enemy name tag opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_enemy_name_font_size", "Floating enemy name tag font scale.", 1.5F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_enemy_name_offset_z", "Floating enemy name tag vertical world offset.", 0.75F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_enemy_name_offset_x", "Floating enemy name tag horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_name_offset_y", "Floating enemy name tag vertical screen offset.", -34.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_enemy_name_max_distance", "Hide enemy name tags beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_enemy_name_r", "Floating enemy name tag red channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name_g", "Floating enemy name tag green channel.", 235, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_enemy_name_b", "Floating enemy name tag blue channel.", 235, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_width", "Teammate lightning beam width in pixels.", 2.0F, archivedClient, 1.0F, 12.0F});
  console.registerCvar({"r_teammate_beam_alpha", "Teammate lightning beam opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_beam_r", "Teammate lightning beam red channel.", 80, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_g", "Teammate lightning beam green channel.", 220, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_beam_b", "Teammate lightning beam blue channel.", 150, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_r", "Teammate model red channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_g", "Teammate model green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_b", "Teammate model blue channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_alpha", "Teammate model opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_outline", "Draw teammate screen-space outline.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_outline_width", "Teammate outline width in final display pixels (1-6 px intended).", 3.0F, archivedClient, 0.0F, 6.0F});
  console.registerCvar({"r_teammate_outline_alpha", "Teammate outline opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_outline_r", "Teammate model outline red channel.", 128, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_outline_g", "Teammate model outline green channel.", 240, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_outline_b", "Teammate model outline blue channel.", 255, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_lean", "Enable Q3-style velocity lean on teammate models.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_lean_scale", "Teammate model velocity lean multiplier.", 1.0F, archivedClient, 0.0F, 3.0F});

  console.registerCvar({"r_teammate_health", "Draw floating teammate health bars.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_damage_only", "Only show teammate health bars after recent damage.", false, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_fade", "Fade teammate health bars during their damage-only duration.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_health_duration", "Seconds to show teammate health after damage.", 5.0F, archivedClient, 0.0F, 30.0F});
  console.registerCvar({"r_teammate_health_max_distance", "Hide teammate health bars beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_teammate_health_width", "Floating teammate health bar width in pixels.", 72.0F, archivedClient, 12.0F, 360.0F});
  console.registerCvar({"r_teammate_health_height", "Floating teammate health bar height in pixels.", 7.0F, archivedClient, 2.0F, 60.0F});
  console.registerCvar({"r_teammate_health_offset_z", "Floating teammate health bar vertical world offset.", 0.35F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_teammate_health_offset_x", "Floating teammate health bar horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_health_offset_y", "Floating teammate health bar vertical screen offset.", -18.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_health_alpha", "Floating teammate health bar opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_health_r", "Floating teammate health bar red channel.", 82, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_health_g", "Floating teammate health bar green channel.", 190, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_health_b", "Floating teammate health bar blue channel.", 224, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name", "Draw floating teammate name tags.", true, archivedClient, {}, {}});
  console.registerCvar({"r_teammate_name_alpha", "Floating teammate name tag opacity.", 1.0F, archivedClient, 0.0F, 1.0F});
  console.registerCvar({"r_teammate_name_font_size", "Floating teammate name tag font scale.", 1.5F, archivedClient, 0.5F, 6.0F});
  console.registerCvar({"r_teammate_name_offset_z", "Floating teammate name tag vertical world offset.", 0.75F, archivedClient, -2.0F, 6.0F});
  console.registerCvar({"r_teammate_name_offset_x", "Floating teammate name tag horizontal screen offset.", 0.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_name_offset_y", "Floating teammate name tag vertical screen offset.", -34.0F, archivedClient, -400.0F, 400.0F});
  console.registerCvar({"r_teammate_name_max_distance", "Hide teammate name tags beyond this 3D distance; zero disables the limit.", 0.0F, archivedClient, 0.0F, 1000.0F});
  console.registerCvar({"r_teammate_name_r", "Floating teammate name tag red channel.", 210, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name_g", "Floating teammate name tag green channel.", 245, archivedClient, 0.0F, 255.0F});
  console.registerCvar({"r_teammate_name_b", "Floating teammate name tag blue channel.", 255, archivedClient, 0.0F, 255.0F});
}

} // namespace lg
